### ISSUE TITLE
Plugin not showing up in Heedy menus

### ISSUE THREAD

**Issue by calebtuttle** [heedy/heedy-notebook-plugin#5]
I've installed the plugin by cloning the git repository and uploading the zip file to heedy. When I navigate to More > Apps, the Notebooks app is listed. But I cannot find an option to create or open a notebook within heedy.

How can I use the notebook plugin?

**Comment by dkumor** [comment]
On your user page, you click the + button, and with the notebook plugin installed, you should have the option of creating a timeseries, and a notebook!

**Comment by calebtuttle** [comment]
> On your user page, you click the + button, and with the notebook plugin installed, you should have the option of creating a timeseries, and a notebook!

Thank you!
